name: ClansPE
author: TRPE Development Team
description: A ClansPE plugin.
version: 3.4.0
main: ClansPE\ClanMain
api: [3.0.0-ALPHA12]
softdepend: ["PureChat", "AntiSpamPro"]
commands:
  clans:
    description: use /clans help
    permission: clanspe.command
permissions:
  clanspe.command:
    default: true
    description: "Allow use of all clanspe commands"
